# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 00:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=64)),
                ('privacy', models.CharField(choices=[('1', 'Public'), ('2', 'Semi-Public'), ('3', 'Semi-Private'), ('4', 'Private')], max_length=1)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
